"""Baseline schema — creates all Phase 0 tables from the ORM metadata.

Subsequent migrations should be hand-authored or autogenerated as the schema
evolves. This baseline intentionally builds directly from Base.metadata so the
initial scaffold and the models can't drift.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-20
"""
from typing import Sequence, Union

from alembic import op

from app.core.db import Base
import app.models  # noqa: F401  (registers all models on Base.metadata)

revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
